# Use a imagem oficial do Node.js como base
FROM node:16

# Diretório de trabalho dentro do container
WORKDIR /app

# Copiar o arquivo package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install -g typescript && npm instal

# Copiar o restante dos arquivos para o diretório de trabalho
COPY . .

# Compile o código TypeScript
RUN tsc
# Exponha a porta que a aplicação irá escutar
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["node", "./dist/index.js"]